### ISSUE TITLE
Crash after Initializing Game

### ISSUE THREAD

**Issue by Pump-Codes** [Evergreen-Client/Evergreen-1.8.9#4]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/11/21 9:52 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.evergreenclient.client.mod.Mod.saveSettings(Mod.java:233)
	at com.evergreenclient.client.mod.Mod.loadSettings(Mod.java:190)
	at com.evergreenclient.client.mod.ModManager.loadModSettings(ModManager.java:85)
	at com.evergreenclient.client.Evergreen.init(Evergreen.java:75)
	at net.minecraft.client.Minecraft.handler$injectModInit$zzd000(Minecraft.java:3405)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561)
	at net.minecraft.client.Minecraft.run(Minecraft.java:362)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.evergreenclient.client.mod.Mod.saveSettings(Mod.java:233)
	at com.evergreenclient.client.mod.Mod.loadSettings(Mod.java:190)
	at com.evergreenclient.client.mod.ModManager.loadModSettings(ModManager.java:85)
	at com.evergreenclient.client.Evergreen.init(Evergreen.java:75)
	at net.minecraft.client.Minecraft.handler$injectModInit$zzd000(Minecraft.java:3405)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:561)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:362)
	at net.minecraft.client.main.Main.main(Main.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 364115648 bytes (347 MB) / 807403520 bytes (770 MB) up to 7622623232 bytes (7269 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce RTX 2060 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.72, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz

**Comment by isXander** [comment]
Known bug with the saving system.

**Comment by Pump-Codes** [comment]
> Known bug with the saving system.

Is there a way to fix this?

**Comment by isXander** [comment]
> > Known bug with the saving system.
> 
> Is there a way to fix this?

You can delete all the config files in the Evergreen folder in your working directory to successfully launch the client

**Comment by Pump-Codes** [comment]
> > > Known bug with the saving system.
> > 
> > 
> > Is there a way to fix this?
> 
> You can delete all the config files in the Evergreen folder in your working directory to successfully launch the client

Now having this error not to sure what it means.

Execution failed for task ':runClient'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_281\bin\java.exe'' finished with non-zero exit value -1

**Comment by Pump-Codes** [comment]
![image](https://user-images.githubusercontent.com/74673280/110968211-42a3ed00-8325-11eb-9d0a-3a0c55999949.png)

This is my startup in IntelliJ that gradlew created.

**Comment by Pump-Codes** [comment]
Also tried the generated args for intellij from gradlew and I get the first error I showed you

**Comment by Pump-Codes** [comment]
also do you have a .json file to go with the client when imported into Minecraft launcher?

**Comment by Pump-Codes** [comment]
I find mod eerorr 

[11:49:07] [Client thread/WARN]: Failed to load Extra Controls Mod, defaulting settings.
[11:49:07] [Client thread/INFO]: Saving Extra Controls Mod.
[11:49:07] [Client thread/INFO]: Loading Low Hp Tint Mod.
[11:49:07] [Client thread/WARN]: Failed to load Low Hp Tint Mod, defaulting settings.
[11:49:07] [Client thread/INFO]: Saving Low Hp Tint Mod.

**Comment by isXander** [comment]
> > > > Known bug with the saving system.
> > > 
> > > 
> > > Is there a way to fix this?
> > 
> > 
> > You can delete all the config files in the Evergreen folder in your working directory to successfully launch the client
> 
> Now having this error not to sure what it means.
> 
> Execution failed for task ':runClient'.
> 
> > Process 'command 'C:\Program Files\Java\jdk1.8.0_281\bin\java.exe'' finished with non-zero exit value -1

[here is what you need to do](https://i.imgur.com/W2bHzYW.gif)
there is no json file for evergreen as it is not a standalone client. You should not be using this client for daily use as it is not ready

**Comment by ItzMeBlaze** [comment]
xander dont publish it if its not ready please put "beta" in the title.

**Comment by isXander** [comment]
this is a dead client
